### PR TITLE
Updated on 15-FEB-2017 to fix CHECK_DOOR_STATE bug

### PR DESCRIPTION
**Pull request by tigerbrain**
Fix an issue with function CHECK_DOOR_STATE that is always returning a value of 1 and not checking against the actual door state of the garage.

### CODE REVIEW

**Comment by sammyk77** [comment]
Looks like the numbers in lines 59-72 also need to be in quotes again.

**Comment by tigerbrain** [comment]
Thanks for bringing that to my attention @sammyk77.

tigerbrain

**Comment by SConaway** [comment]
Thanks @tigerbrain. It works perfectly!

**Comment by jschollenberger** [comment]
Thank you!

**Comment by jbnunn** [comment]
Thanks all!

**Pull request merged**
