### PR TITLE
Added support for new DeviceId; Updated README

### PR DESCRIPTION
**Pull request by wblakecaldwell**
- Added support for device named 'Garage Door Opener WGDO'
- README.md: Added zip command - You can't just zip up the parent directory.
- README.md: Handler function prefix is the file name - "main.", not "lambda_function."

### CODE REVIEW

**Comment by JosePadron** [comment]
Thank you for fixing the README!

**Comment by bhusang** [comment]
I used your updated files and had it working easily! Thanks.

**Comment by wblakecaldwell** [comment]
@jbnunn - can you merge this? People are referring to my README from multiple issues. Thanks :)

**Comment by jbnunn** [comment]
Sorry @wblakecaldwell  ... had notifications going to a folder i wasn't checking, I'm on top of this now :)

**Comment by wblakecaldwell** [comment]
Thanks! :)

**Pull request merged**
