### PR TITLE
Breakout MyQ interactions into its own class and add support for a MyQ Lamp module

### PR DESCRIPTION
**Pull request by robrighter**
I use this Alexa app along side some web hooks (for IFTT triggers.) By breaking out the MyQ interactions into its own file people like me can use the same file to support both the Alexa app and the web hooks. This means that we wont have to manually update the api changes.

I also added support for the MyQ Lamp module (http://www.chamberlain.com/smartphone-control-products/lighting-controls/myq-remote-lamp-control) Currently, lamp support is just in the class file not in the Alexa intents, but it could easily be added there.

### CODE REVIEW

**Review by tigerbrain — COMMENTED** [review]
Though I believe these proposed changes would make the code set better, I think it is best to house the changes on a separate repository as the introduction of the separate file though advantageous does somewhat add a layer of complexity to an otherwise simple and effective code set that's already somewhat understood by many. 

However, If these changes do get approved by jbnunn, I would like to suggest that the initiator also takes the time to edit the step by step instructions to keep it current and aligned with the changes proposed here.

**Comment by robrighter** [comment]
I did include an update to the readme that covers the changes. It did not change the setup process much, there is just an additional file that needed to be added to the zip command.

**Comment by tigerbrain** [comment]
Hi @robrighter, on top of updating the README file, you should also update the "StepByStepInstructions" file to make your proposed changes complete.  It's a fairly new file that got added to the repository recently, so I understand why you may have missed it.  But some implementers are already referring to the file for instructions, so It would help to keep it updated particularly for these type of proposed changes.

**Comment by robrighter** [comment]
@tigerbrain no problem. Done.

**Comment by SConaway** [comment]
@robrighter you may want the Garage Door and Lamp Module to be separate files.

**Comment by robrighter** [comment]
@jbnunn is this something you are willing to merge?

**Comment by jbnunn** [comment]
Sorry all, let me review this this weekend and make updates and merges. thank you for the contributions

**Pull request merged**
